# Generated by Django 3.2.16 on 2023-10-01 08:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=' ', error_messages={'unique': 'User with this phone number already exists.'}, max_length=15, region='KZ', unique=True, verbose_name='phone'),
            preserve_default=False,
        ),
    ]
