# Generated by Django 3.2.16 on 2023-10-01 08:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20231001_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'unique': 'User with this phone number already exists.'}, max_length=18, region='KZ', unique=True, verbose_name='phone'),
        ),
    ]
