# Generated by Django 3.2.16 on 2023-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User with this email already registered'}, max_length=254, unique=True, verbose_name='email'),
        ),
    ]
