# Generated by Django 3.2.16 on 2023-10-05 12:39

import django.core.validators
from django.db import migrations, models
import restaurant.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Menu category')),
                ('slug', models.SlugField(unique=True, verbose_name='Shortcut')),
            ],
            options={
                'verbose_name': 'Menu category',
                'verbose_name_plural': 'Menu categories',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description_short', models.TextField(verbose_name='Short description')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1, message='Minimum price is 1'), django.core.validators.MaxValueValidator(10000, message='Maximum price is 10000')], verbose_name='Price')),
                ('is_served', models.BooleanField(verbose_name='Is served')),
                ('on_homepage', models.BooleanField(default=False, verbose_name='Is on the homepage')),
            ],
            options={
                'verbose_name': 'Dish',
                'verbose_name_plural': 'Dishes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(validators=[restaurant.validators.datetime_validator], verbose_name='Reservation date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('party_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Minimum number of guests is 1'), django.core.validators.MaxValueValidator(8, message='Maximum number of guests is 8')], verbose_name='Number of guests')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=255)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('date_time', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Table number')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimum number of seats is 1'), django.core.validators.MaxValueValidator(8, message='Maximum number of seats is 8')], verbose_name='Number of seats available at the table')),
                ('is_active', models.BooleanField(verbose_name='Is active')),
            ],
        ),
    ]
