# Generated by Django 3.2.16 on 2023-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description_short',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
