# Generated by Django 3.2.16 on 2023-09-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dish_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_short',
            field=models.TextField(verbose_name='Short description'),
        ),
    ]
