# Generated by Django 3.2.16 on 2023-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20230924_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='on_homepage',
            field=models.BooleanField(default=False, verbose_name='Is on the homepage'),
            preserve_default=False,
        ),
    ]
