# Generated by Django 3.2.16 on 2023-10-04 06:33

from django.db import migrations, models
from datetime import time


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=time(10, 0), verbose_name='Time of reservation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(verbose_name='Date of reservation'),
        ),
    ]
