# Generated by Django 3.2.16 on 2023-10-04 10:30

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20231004_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('date_time', '-created_at'), 'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(default=timezone.now, verbose_name='Reservation date'),
            preserve_default=False,
        ),
    ]
