# Generated by Django 3.2.16 on 2023-10-04 10:38

from django.db import migrations, models
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20231004_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(validators=[restaurant.validators.datetime_validator], verbose_name='Reservation date'),
        ),
    ]
